### ISSUE TITLE
Refining the rvm specification

### ISSUE THREAD

**Issue by hrszpuk** [hrszpuk/rvm#32]
Specification is missing a lot of information.

### Section Ideas
- [x] Architecture
  - [x] Overview
  - [x] Call Stack
  - [x] Instruction Buffer
  - [x] Registers
  - [x] Variable Pool
  - [x] Multi-threading
  - [x] Opcode Stream
  - [x] Dynamic Binary Loading
- [x] Instruction Set
  - [x] Overview
  - [x] Human-readable bytecode 
    - [x] Bytecode format 
    - [x] Macros
  - [x] Opcode 
    - [x] Opcode format
  - [x] Code Block
    - [x] Stack Management
    - [x] Arithmetic and Logic
    - [x] Store/Load
    - [x] Type Conversions
    - [x] Control Flow
    - [x] Subroutines
  - [x] Data Block
    - [x] Constants
    - [x] Variables
    - [x] Structures
  - [x] Metadata Block 
- [x] Code base
  - [x] Translation module: translates human readable bytecode to actual opcodes
  - [x] VM module: interprets opcodes
  - [x] Data Structures: Stack, Dictionary, Heap, Buffer

**Comment by Khhs167** [comment]
I'd like to suggest something like metadata, or just a "binary layout"

If we look at runtimes like the .NET CLI, the binaries all store where different functions, classes and values are stored. I believe this could be very important for anyone wishing to develop a language for RVM, plus it helps with debugging(since you can store stuff like variable locations in the metadata).

This could go hand-in-hand with assembly-style regions(splitting the code into multiple parts), where there's one region(maybe at the start), which just lists any symbols or other metadata we might need.

Not sure how to do it, but it would be useful.

**Comment by Khhs167** [comment]
It depends on what we want to achieve.

My general idea was something in the likes of(in my assembler style here ofc)
```asm
.META

.str "function_a" .const function_a ; Simple lookup table

.CODE

function_a:
    ; Whatever

```

With a macro we'd be able to do smth like

```asm
.export $1

; Expands to:

.META
.str "$1" .const $1
```

Not the assembly style you where thinking maybe, but I feel like each binary declaring a table of symbols is the most important thing here

**Comment by Khhs167** [comment]
Sound good!

**Comment by Khhs167** [comment]
Oh and, before I forget...
Should `out` really be kept in the spec?

It could just be made part of the standard library?
